name: ieltspracticegroup
version: 1

libraries:
- name: flask
  version: "0.10.1"
- name: flask-sqlalchemy
  version: "2.0"
- name: flask-login
  version: "0.2.11"
- name: flask-script
  version: "2.0.5"
- name: flask-bootstrap
  version: "3.3.4.1"
- name: flask-wtf
  version: "0.11"
- name: sqlalchemy
  version: "0.9.9"
- name: jinja2
  version: "2.7.3"
- name: wtforms
  version: "2.0.2"
- name: itsdangerous
  version: "0.24"
- name: markupsafe
  version: "0.23"
- name: flask-mail
  version: "0.9.1"
  